// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// A2APublicationRepositoryMock is a mock implementation of repositories.A2APublicationRepository.
//
//	func TestSomethingThatUsesA2APublicationRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.A2APublicationRepository
//		mockedA2APublicationRepository := &A2APublicationRepositoryMock{
//			ClaimDueFunc: func(ctx context.Context, now time.Time, limit int) ([]models.A2APublication, error) {
//				panic("mock out the ClaimDue method")
//			},
//			DeleteForAgentFunc: func(ctx context.Context, ouID string, projectName string, agentName string) error {
//				panic("mock out the DeleteForAgent method")
//			},
//			EnqueueFunc: func(ctx context.Context, pub *models.A2APublication) error {
//				panic("mock out the Enqueue method")
//			},
//			FindPublishedFunc: func(ctx context.Context, afterID uuid.UUID, limit int) ([]models.A2APublication, error) {
//				panic("mock out the FindPublished method")
//			},
//			MarkAttemptFailedFunc: func(ctx context.Context, read models.A2APublication, lastErr string, nextAttemptAt time.Time) error {
//				panic("mock out the MarkAttemptFailed method")
//			},
//			MarkFailedFunc: func(ctx context.Context, read models.A2APublication, lastErr string) error {
//				panic("mock out the MarkFailed method")
//			},
//			MarkPublishedFunc: func(ctx context.Context, read models.A2APublication, upstreamURL string) error {
//				panic("mock out the MarkPublished method")
//			},
//			MarkWaitingFunc: func(ctx context.Context, read models.A2APublication, reason string, nextAttemptAt time.Time) error {
//				panic("mock out the MarkWaiting method")
//			},
//			RequeueFunc: func(ctx context.Context, read models.A2APublication) error {
//				panic("mock out the Requeue method")
//			},
//		}
//
//		// use mockedA2APublicationRepository in code that requires repositories.A2APublicationRepository
//		// and then make assertions.
//
//	}
type A2APublicationRepositoryMock struct {
	// ClaimDueFunc mocks the ClaimDue method.
	ClaimDueFunc func(ctx context.Context, now time.Time, limit int) ([]models.A2APublication, error)

	// DeleteForAgentFunc mocks the DeleteForAgent method.
	DeleteForAgentFunc func(ctx context.Context, ouID string, projectName string, agentName string) error

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, pub *models.A2APublication) error

	// FindPublishedFunc mocks the FindPublished method.
	FindPublishedFunc func(ctx context.Context, afterID uuid.UUID, limit int) ([]models.A2APublication, error)

	// MarkAttemptFailedFunc mocks the MarkAttemptFailed method.
	MarkAttemptFailedFunc func(ctx context.Context, read models.A2APublication, lastErr string, nextAttemptAt time.Time) error

	// MarkFailedFunc mocks the MarkFailed method.
	MarkFailedFunc func(ctx context.Context, read models.A2APublication, lastErr string) error

	// MarkPublishedFunc mocks the MarkPublished method.
	MarkPublishedFunc func(ctx context.Context, read models.A2APublication, upstreamURL string) error

	// MarkWaitingFunc mocks the MarkWaiting method.
	MarkWaitingFunc func(ctx context.Context, read models.A2APublication, reason string, nextAttemptAt time.Time) error

	// RequeueFunc mocks the Requeue method.
	RequeueFunc func(ctx context.Context, read models.A2APublication) error

	// calls tracks calls to the methods.
	calls struct {
		// ClaimDue holds details about calls to the ClaimDue method.
		ClaimDue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Now is the now argument value.
			Now time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// DeleteForAgent holds details about calls to the DeleteForAgent method.
		DeleteForAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pub is the pub argument value.
			Pub *models.A2APublication
		}
		// FindPublished holds details about calls to the FindPublished method.
		FindPublished []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AfterID is the afterID argument value.
			AfterID uuid.UUID
			// Limit is the limit argument value.
			Limit int
		}
		// MarkAttemptFailed holds details about calls to the MarkAttemptFailed method.
		MarkAttemptFailed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Read is the read argument value.
			Read models.A2APublication
			// LastErr is the lastErr argument value.
			LastErr string
			// NextAttemptAt is the nextAttemptAt argument value.
			NextAttemptAt time.Time
		}
		// MarkFailed holds details about calls to the MarkFailed method.
		MarkFailed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Read is the read argument value.
			Read models.A2APublication
			// LastErr is the lastErr argument value.
			LastErr string
		}
		// MarkPublished holds details about calls to the MarkPublished method.
		MarkPublished []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Read is the read argument value.
			Read models.A2APublication
			// UpstreamURL is the upstreamURL argument value.
			UpstreamURL string
		}
		// MarkWaiting holds details about calls to the MarkWaiting method.
		MarkWaiting []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Read is the read argument value.
			Read models.A2APublication
			// Reason is the reason argument value.
			Reason string
			// NextAttemptAt is the nextAttemptAt argument value.
			NextAttemptAt time.Time
		}
		// Requeue holds details about calls to the Requeue method.
		Requeue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Read is the read argument value.
			Read models.A2APublication
		}
	}
	lockClaimDue          sync.RWMutex
	lockDeleteForAgent    sync.RWMutex
	lockEnqueue           sync.RWMutex
	lockFindPublished     sync.RWMutex
	lockMarkAttemptFailed sync.RWMutex
	lockMarkFailed        sync.RWMutex
	lockMarkPublished     sync.RWMutex
	lockMarkWaiting       sync.RWMutex
	lockRequeue           sync.RWMutex
}

// ClaimDue calls ClaimDueFunc.
func (mock *A2APublicationRepositoryMock) ClaimDue(ctx context.Context, now time.Time, limit int) ([]models.A2APublication, error) {
	if mock.ClaimDueFunc == nil {
		panic("A2APublicationRepositoryMock.ClaimDueFunc: method is nil but A2APublicationRepository.ClaimDue was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Now   time.Time
		Limit int
	}{
		Ctx:   ctx,
		Now:   now,
		Limit: limit,
	}
	mock.lockClaimDue.Lock()
	mock.calls.ClaimDue = append(mock.calls.ClaimDue, callInfo)
	mock.lockClaimDue.Unlock()
	return mock.ClaimDueFunc(ctx, now, limit)
}

// ClaimDueCalls gets all the calls that were made to ClaimDue.
// Check the length with:
//
//	len(mockedA2APublicationRepository.ClaimDueCalls())
func (mock *A2APublicationRepositoryMock) ClaimDueCalls() []struct {
	Ctx   context.Context
	Now   time.Time
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Now   time.Time
		Limit int
	}
	mock.lockClaimDue.RLock()
	calls = mock.calls.ClaimDue
	mock.lockClaimDue.RUnlock()
	return calls
}

// DeleteForAgent calls DeleteForAgentFunc.
func (mock *A2APublicationRepositoryMock) DeleteForAgent(ctx context.Context, ouID string, projectName string, agentName string) error {
	if mock.DeleteForAgentFunc == nil {
		panic("A2APublicationRepositoryMock.DeleteForAgentFunc: method is nil but A2APublicationRepository.DeleteForAgent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
		AgentName   string
	}{
		Ctx:         ctx,
		OuID:        ouID,
		ProjectName: projectName,
		AgentName:   agentName,
	}
	mock.lockDeleteForAgent.Lock()
	mock.calls.DeleteForAgent = append(mock.calls.DeleteForAgent, callInfo)
	mock.lockDeleteForAgent.Unlock()
	return mock.DeleteForAgentFunc(ctx, ouID, projectName, agentName)
}

// DeleteForAgentCalls gets all the calls that were made to DeleteForAgent.
// Check the length with:
//
//	len(mockedA2APublicationRepository.DeleteForAgentCalls())
func (mock *A2APublicationRepositoryMock) DeleteForAgentCalls() []struct {
	Ctx         context.Context
	OuID        string
	ProjectName string
	AgentName   string
} {
	var calls []struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
		AgentName   string
	}
	mock.lockDeleteForAgent.RLock()
	calls = mock.calls.DeleteForAgent
	mock.lockDeleteForAgent.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *A2APublicationRepositoryMock) Enqueue(ctx context.Context, pub *models.A2APublication) error {
	if mock.EnqueueFunc == nil {
		panic("A2APublicationRepositoryMock.EnqueueFunc: method is nil but A2APublicationRepository.Enqueue was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pub *models.A2APublication
	}{
		Ctx: ctx,
		Pub: pub,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, pub)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedA2APublicationRepository.EnqueueCalls())
func (mock *A2APublicationRepositoryMock) EnqueueCalls() []struct {
	Ctx context.Context
	Pub *models.A2APublication
} {
	var calls []struct {
		Ctx context.Context
		Pub *models.A2APublication
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// FindPublished calls FindPublishedFunc.
func (mock *A2APublicationRepositoryMock) FindPublished(ctx context.Context, afterID uuid.UUID, limit int) ([]models.A2APublication, error) {
	if mock.FindPublishedFunc == nil {
		panic("A2APublicationRepositoryMock.FindPublishedFunc: method is nil but A2APublicationRepository.FindPublished was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		AfterID uuid.UUID
		Limit   int
	}{
		Ctx:     ctx,
		AfterID: afterID,
		Limit:   limit,
	}
	mock.lockFindPublished.Lock()
	mock.calls.FindPublished = append(mock.calls.FindPublished, callInfo)
	mock.lockFindPublished.Unlock()
	return mock.FindPublishedFunc(ctx, afterID, limit)
}

// FindPublishedCalls gets all the calls that were made to FindPublished.
// Check the length with:
//
//	len(mockedA2APublicationRepository.FindPublishedCalls())
func (mock *A2APublicationRepositoryMock) FindPublishedCalls() []struct {
	Ctx     context.Context
	AfterID uuid.UUID
	Limit   int
} {
	var calls []struct {
		Ctx     context.Context
		AfterID uuid.UUID
		Limit   int
	}
	mock.lockFindPublished.RLock()
	calls = mock.calls.FindPublished
	mock.lockFindPublished.RUnlock()
	return calls
}

// MarkAttemptFailed calls MarkAttemptFailedFunc.
func (mock *A2APublicationRepositoryMock) MarkAttemptFailed(ctx context.Context, read models.A2APublication, lastErr string, nextAttemptAt time.Time) error {
	if mock.MarkAttemptFailedFunc == nil {
		panic("A2APublicationRepositoryMock.MarkAttemptFailedFunc: method is nil but A2APublicationRepository.MarkAttemptFailed was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		Read          models.A2APublication
		LastErr       string
		NextAttemptAt time.Time
	}{
		Ctx:           ctx,
		Read:          read,
		LastErr:       lastErr,
		NextAttemptAt: nextAttemptAt,
	}
	mock.lockMarkAttemptFailed.Lock()
	mock.calls.MarkAttemptFailed = append(mock.calls.MarkAttemptFailed, callInfo)
	mock.lockMarkAttemptFailed.Unlock()
	return mock.MarkAttemptFailedFunc(ctx, read, lastErr, nextAttemptAt)
}

// MarkAttemptFailedCalls gets all the calls that were made to MarkAttemptFailed.
// Check the length with:
//
//	len(mockedA2APublicationRepository.MarkAttemptFailedCalls())
func (mock *A2APublicationRepositoryMock) MarkAttemptFailedCalls() []struct {
	Ctx           context.Context
	Read          models.A2APublication
	LastErr       string
	NextAttemptAt time.Time
} {
	var calls []struct {
		Ctx           context.Context
		Read          models.A2APublication
		LastErr       string
		NextAttemptAt time.Time
	}
	mock.lockMarkAttemptFailed.RLock()
	calls = mock.calls.MarkAttemptFailed
	mock.lockMarkAttemptFailed.RUnlock()
	return calls
}

// MarkFailed calls MarkFailedFunc.
func (mock *A2APublicationRepositoryMock) MarkFailed(ctx context.Context, read models.A2APublication, lastErr string) error {
	if mock.MarkFailedFunc == nil {
		panic("A2APublicationRepositoryMock.MarkFailedFunc: method is nil but A2APublicationRepository.MarkFailed was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Read    models.A2APublication
		LastErr string
	}{
		Ctx:     ctx,
		Read:    read,
		LastErr: lastErr,
	}
	mock.lockMarkFailed.Lock()
	mock.calls.MarkFailed = append(mock.calls.MarkFailed, callInfo)
	mock.lockMarkFailed.Unlock()
	return mock.MarkFailedFunc(ctx, read, lastErr)
}

// MarkFailedCalls gets all the calls that were made to MarkFailed.
// Check the length with:
//
//	len(mockedA2APublicationRepository.MarkFailedCalls())
func (mock *A2APublicationRepositoryMock) MarkFailedCalls() []struct {
	Ctx     context.Context
	Read    models.A2APublication
	LastErr string
} {
	var calls []struct {
		Ctx     context.Context
		Read    models.A2APublication
		LastErr string
	}
	mock.lockMarkFailed.RLock()
	calls = mock.calls.MarkFailed
	mock.lockMarkFailed.RUnlock()
	return calls
}

// MarkPublished calls MarkPublishedFunc.
func (mock *A2APublicationRepositoryMock) MarkPublished(ctx context.Context, read models.A2APublication, upstreamURL string) error {
	if mock.MarkPublishedFunc == nil {
		panic("A2APublicationRepositoryMock.MarkPublishedFunc: method is nil but A2APublicationRepository.MarkPublished was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Read        models.A2APublication
		UpstreamURL string
	}{
		Ctx:         ctx,
		Read:        read,
		UpstreamURL: upstreamURL,
	}
	mock.lockMarkPublished.Lock()
	mock.calls.MarkPublished = append(mock.calls.MarkPublished, callInfo)
	mock.lockMarkPublished.Unlock()
	return mock.MarkPublishedFunc(ctx, read, upstreamURL)
}

// MarkPublishedCalls gets all the calls that were made to MarkPublished.
// Check the length with:
//
//	len(mockedA2APublicationRepository.MarkPublishedCalls())
func (mock *A2APublicationRepositoryMock) MarkPublishedCalls() []struct {
	Ctx         context.Context
	Read        models.A2APublication
	UpstreamURL string
} {
	var calls []struct {
		Ctx         context.Context
		Read        models.A2APublication
		UpstreamURL string
	}
	mock.lockMarkPublished.RLock()
	calls = mock.calls.MarkPublished
	mock.lockMarkPublished.RUnlock()
	return calls
}

// MarkWaiting calls MarkWaitingFunc.
func (mock *A2APublicationRepositoryMock) MarkWaiting(ctx context.Context, read models.A2APublication, reason string, nextAttemptAt time.Time) error {
	if mock.MarkWaitingFunc == nil {
		panic("A2APublicationRepositoryMock.MarkWaitingFunc: method is nil but A2APublicationRepository.MarkWaiting was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		Read          models.A2APublication
		Reason        string
		NextAttemptAt time.Time
	}{
		Ctx:           ctx,
		Read:          read,
		Reason:        reason,
		NextAttemptAt: nextAttemptAt,
	}
	mock.lockMarkWaiting.Lock()
	mock.calls.MarkWaiting = append(mock.calls.MarkWaiting, callInfo)
	mock.lockMarkWaiting.Unlock()
	return mock.MarkWaitingFunc(ctx, read, reason, nextAttemptAt)
}

// MarkWaitingCalls gets all the calls that were made to MarkWaiting.
// Check the length with:
//
//	len(mockedA2APublicationRepository.MarkWaitingCalls())
func (mock *A2APublicationRepositoryMock) MarkWaitingCalls() []struct {
	Ctx           context.Context
	Read          models.A2APublication
	Reason        string
	NextAttemptAt time.Time
} {
	var calls []struct {
		Ctx           context.Context
		Read          models.A2APublication
		Reason        string
		NextAttemptAt time.Time
	}
	mock.lockMarkWaiting.RLock()
	calls = mock.calls.MarkWaiting
	mock.lockMarkWaiting.RUnlock()
	return calls
}

// Requeue calls RequeueFunc.
func (mock *A2APublicationRepositoryMock) Requeue(ctx context.Context, read models.A2APublication) error {
	if mock.RequeueFunc == nil {
		panic("A2APublicationRepositoryMock.RequeueFunc: method is nil but A2APublicationRepository.Requeue was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Read models.A2APublication
	}{
		Ctx:  ctx,
		Read: read,
	}
	mock.lockRequeue.Lock()
	mock.calls.Requeue = append(mock.calls.Requeue, callInfo)
	mock.lockRequeue.Unlock()
	return mock.RequeueFunc(ctx, read)
}

// RequeueCalls gets all the calls that were made to Requeue.
// Check the length with:
//
//	len(mockedA2APublicationRepository.RequeueCalls())
func (mock *A2APublicationRepositoryMock) RequeueCalls() []struct {
	Ctx  context.Context
	Read models.A2APublication
} {
	var calls []struct {
		Ctx  context.Context
		Read models.A2APublication
	}
	mock.lockRequeue.RLock()
	calls = mock.calls.Requeue
	mock.lockRequeue.RUnlock()
	return calls
}
